language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: 1++cElc+aSDzqy9P8Y6fznxjXuYSSwr2WCkvryPV5Cmi8N5bMX57RpGKjDsGgekNIZNMZi7URcWz/46FckkUOm34/P1IHFXz23Ik3CcO2zGqz3zUndd/YT4mQ22hzOpY1FlEEwQ1NwXoi4vpt2bcUYWJWDgBMbEYqwv7x2E/qG/r736KBICGJyobNrDpg8vHob0CxbsWLfc2ZkqMRiGzh1TTAGLAcHqOvU2fPi3FcFIyW646/P2M1ztA2N2K4lcT5HY3Pl/q6AboUeIPqAFSPzArRDBokal5TH8CDUnV8Nc/pxLNAZkaAqxfIDdeafWc33Naz4ARcAYExsmeHD4X+vL1VFy4VdEBtd7q7OTLD2WCz9p2wfg13ZcFK6vZzci9U3lGAQ3Lo4BWeP4o1VCaNDbb5WJz1hXpBaIUTKtOZEcEvlPpjkDZ4BaT7eSEYZ15o0G9BJXbtuVDLTJIkqxU4J3zcv+Wy2hofklaWNYoAx41orzQ1cmHgv5knX97VnoyFi6z5jqA+cs+FPr/CQ3gKwpRv78Nmh205p1bVz3rfUH6xIv6FqNezq6KYj59s5sHanc8rbrYEm3jxF8DLoMdBJtYmpRNZavTakkJtrct/e93+Cpl3kb15TW60uvnoMfkKVXzMAgKYB5OqBRnMoUEpvUUAl58W/b36GF+AcZ6G2w=
  app: solar-garden-be
  on:
    repo: My-Solar-Garden/rails_backend
    branch: main
  skip_cleanup: 'true'
